@startuml
interface CartMapper {
+ List<CartVO> cartList(Map<String,Object>)
+ Integer cartRowCount(Map<String,Object>)
~ int checkCartItem(CartVO)
~ void updateCartQuantity(CartVO)
~ void insertCart(CartVO)
+ void deleteCart(int)
~ CartVO selectCart(int)
+ void updateCartQuantityByCartNum(int,int)
+ List<CartVO> deleteCartsByMember(long)
}

interface CartService {
+ void insertOrUpdateCart(CartVO)
+ List<CartVO> cartList(Map<String,Object>)
+ Integer cartRowCount(Map<String,Object>)
+ void deleteCart(int)
+ void updateCartQuantity(int,int)
}

class CartServiceImpl {
~ CartMapper cartMapper
+ void insertOrUpdateCart(CartVO)
+ List<CartVO> cartList(Map<String,Object>)
+ Integer cartRowCount(Map<String,Object>)
+ void deleteCart(int)
+ void updateCartQuantity(int,int)
}


class CartVO {
- long cart_num
- long item_num
- long mem_num
- Long cart_quantity
- long purchase_num
- int item_price
- GoodsVO goods
}

class CartController {
- CartService cartService
+ CartVO initCommand()
+ String insertCart(long,long,int,Long,HttpServletRequest,Model)
+ String getList(int,Model,HttpSession)
+ String deleteCart(int)
+ String deleteSelectedCarts(List<Integer>)
+ String updateCartQuantity(int,int)
}




CartService <|.. CartServiceImpl
@enduml