@startuml
class kr.spring.category.controller.CategoryAjaxController {
- CategoryService categoryService
+ Map<String,String> processFile(Long,HttpSession,HttpServletRequest)
}


interface kr.spring.category.dao.CategoryMapper {
+ void insertDonationCategory(DonationCategoryVO)
+ int getListCount(Map<String,Object>)
+ List<DonationCategoryVO> selectList()
+ List<DonationCategoryVO> selectListNoPage()
+ DonationCategoryVO selectDonationCategory(Long)
+ void updateDonationCategory(DonationCategoryVO)
+ void deleteDonationCategory(Long)
+ void deleteFile(Long)
+ void insertChallengeCategory(ChallengeCategoryVO)
+ int getChalCateCount(Map<String,Object>)
+ List<ChallengeCategoryVO> selectChalCateList()
+ ChallengeCategoryVO selectChallengeCategory(Long)
+ void updateChallengeCategory(ChallengeCategoryVO)
+ void deleteChallengeCategory(Long)
}

interface kr.spring.category.service.CategoryService {
+ void insertDonationCategory(DonationCategoryVO)
+ int getListCount(Map<String,Object>)
+ List<DonationCategoryVO> selectList()
+ List<DonationCategoryVO> selectListNoPage()
+ DonationCategoryVO selectDonationCategory(Long)
+ void updateDonationCategory(DonationCategoryVO)
+ void deleteDonationCategory(Long)
+ void deleteFile(Long)
+ void insertChallengeCategory(ChallengeCategoryVO)
+ int getChalCateCount(Map<String,Object>)
+ List<ChallengeCategoryVO> selectChalCateList()
+ ChallengeCategoryVO selectChallengeCategory(Long)
+ void updateChallengeCategory(ChallengeCategoryVO)
+ void deleteChallengeCategory(Long)
}

class kr.spring.category.vo.ChallengeCategoryVO {
- int ccate_num
- String ccate_name
}

class kr.spring.category.controller.CategoryController {
- CategoryService categoryService
- PayuidService payuidService
+ String categoryList(Model)
+ String insertCategoryForm(Model)
+ ModelAndView detailCategory(long,HttpSession,Model)
+ String submitDelete(long,HttpServletRequest)
+ String formUpdate(long,Model)
+ String submitUpdate(DonationCategoryVO,BindingResult,Model,HttpServletRequest)
}


class kr.spring.category.controller.CategoryController$DonationCategoryController {
- CategoryService categoryService
+ String submit(DonationCategoryVO,BindingResult,HttpServletRequest,HttpSession,Model)
}


class kr.spring.category.service.CategoryServiceImpl {
~ CategoryMapper categoryMapper
+ void insertDonationCategory(DonationCategoryVO)
+ List<DonationCategoryVO> selectList()
+ List<DonationCategoryVO> selectListNoPage()
+ DonationCategoryVO selectDonationCategory(Long)
+ void updateDonationCategory(DonationCategoryVO)
+ void deleteDonationCategory(Long)
+ int getListCount(Map<String,Object>)
+ void deleteFile(Long)
+ void insertChallengeCategory(ChallengeCategoryVO)
+ int getChalCateCount(Map<String,Object>)
+ List<ChallengeCategoryVO> selectChalCateList()
+ ChallengeCategoryVO selectChallengeCategory(Long)
+ void updateChallengeCategory(ChallengeCategoryVO)
+ void deleteChallengeCategory(Long)
}


class kr.spring.category.vo.DonationCategoryVO {
- long dcate_num
- String dcate_name
- String dcate_charity
- String dcate_icon
- String dcate_content
- String dcate_banner
- MultipartFile iconUpload
- MultipartFile bannerUpload
}



kr.spring.category.controller.CategoryController +.. kr.spring.category.controller.CategoryController$DonationCategoryController
kr.spring.category.service.CategoryService <|.. kr.spring.category.service.CategoryServiceImpl
@enduml