@startuml
class kr.spring.cs.vo.InquiryVO {
- Long inquiry_num
- long mem_num
- Integer inquiry_category
- String inquiry_title
- String inquiry_filename
- String inquiry_content
- String inquiry_reply
- Date inquiry_date
- Date inquiry_rdate
- MultipartFile upload
- String file_deleted
- String mem_nick
- String mem_email
}

class kr.spring.cs.controller.CSController {
~ CSService csService
~ MemberService memberService
+ InquiryVO initInquiryCommand()
+ ReportVO initReportCommand()
+ String faqlist(String,Model)
+ String adminFAQ(String,Model)
+ Map<String,Object> insertFaqAjax(String,String,int,HttpSession)
+ Map<String,Object> modifyFaqAjax(String,String,long,HttpSession)
+ Map<String,Object> deleteFaqAjax(long,HttpSession)
+ String form(Model)
+ String inquiry(InquiryVO,BindingResult,HttpServletRequest,HttpSession,Model)
+ String inquiryList(int,int,HttpSession,Model)
+ String replyInquiryForm(long,Model)
+ String replyInquiry(InquiryVO,BindingResult,Model,HttpServletRequest)
+ String modifyInquiryFormAjax(long,Model)
+ String memberReport(int,String,HttpSession,Model)
+ String replyReportForm(long,Model)
+ String replyReport(ReportVO,BindingResult,Model)
+ String modifyReportFormAjax(long,Model)
+ String formReport(Long,Long,Long,Integer,long,Model,HttpSession)
+ String report(ReportVO,BindingResult,HttpServletRequest,HttpSession,Model)
}


class kr.spring.cs.vo.ReportVO {
- long report_num
- long mem_num
- long reported_mem_num
- Integer report_type
- String report_content
- String report_filename
- String report_reply
- Date report_rdate
- Integer report_status
- Date report_date
- String mem_nick
- String reported_mem_nick
- int reported_mem_status
- Integer report_source
- Long chal_num
- Long chal_rev_num
- Long dbox_re_num
- MultipartFile upload
}

interface kr.spring.cs.service.CSService {
+ void insertInquiry(InquiryVO)
+ InquiryVO selectInquiryDetail(long)
+ List<InquiryVO> selectInquiryList(Map<String,Object>)
+ int selectInquiryListCount(Map<String,Object>)
+ List<InquiryVO> selectInquiryListByMemNum(long)
+ void updateInquiry(InquiryVO)
+ void deleteInquiry(long)
+ void replyInquiry(InquiryVO)
+ List<FaqVO> selectFaqList(Map<String,Object>)
+ long insertFaq(FaqVO)
+ void updateFaq(FaqVO)
+ void deleteFaq(long)
+ void insertReport(ReportVO)
+ int selectReportListCount(Map<String,Object>)
+ List<ReportVO> selectReportList(Map<String,Object>)
+ ReportVO selectReportDetail(long)
+ void replyReport(ReportVO)
+ void deleteReport(long)
+ List<ReportVO> selectReportListByMemNum(long)
}

interface kr.spring.cs.dao.CSMapper {
+ void insertInquiry(InquiryVO)
+ InquiryVO selectInquiryDetail(long)
+ List<InquiryVO> selectInquiryList(Map<String,Object>)
+ int selectInquiryListCount(Map<String,Object>)
+ List<InquiryVO> selectInquiryListByMemNum(long)
+ void updateInquiry(InquiryVO)
+ void deleteInquiry(long)
+ void replyInquiry(InquiryVO)
+ List<FaqVO> selectFaqList(Map<String,Object>)
+ void insertFaq(FaqVO)
+ void updateFaq(FaqVO)
+ void deleteFaq(long)
+ long selectFaqNum()
+ void insertReport(ReportVO)
+ int selectReportListCount(Map<String,Object>)
+ List<ReportVO> selectReportList(Map<String,Object>)
+ ReportVO selectReportDetail(long)
+ void replyReport(ReportVO)
+ void deleteReport(long)
+ List<ReportVO> selectReportListByMemNum(long)
}

class kr.spring.cs.service.CSServiceImpl {
~ CSMapper csMapper
~ MemberMapper memberMapper
~ NotifyService notifyService
+ void insertInquiry(InquiryVO)
+ InquiryVO selectInquiryDetail(long)
+ List<InquiryVO> selectInquiryList(Map<String,Object>)
+ int selectInquiryListCount(Map<String,Object>)
+ List<InquiryVO> selectInquiryListByMemNum(long)
+ void updateInquiry(InquiryVO)
+ void deleteInquiry(long)
+ void replyInquiry(InquiryVO)
+ List<FaqVO> selectFaqList(Map<String,Object>)
+ long insertFaq(FaqVO)
+ void updateFaq(FaqVO)
+ void deleteFaq(long)
+ void insertReport(ReportVO)
+ int selectReportListCount(Map<String,Object>)
+ List<ReportVO> selectReportList(Map<String,Object>)
+ ReportVO selectReportDetail(long)
+ void replyReport(ReportVO)
+ void deleteReport(long)
+ List<ReportVO> selectReportListByMemNum(long)
}


class kr.spring.cs.vo.FaqVO {
- long faq_num
- int faq_category
- String faq_question
- String faq_answer
+ <<Create>> FaqVO(int,String,String)
+ <<Create>> FaqVO(long,String,String)
}




kr.spring.cs.service.CSService <|.. kr.spring.cs.service.CSServiceImpl
@enduml