@startuml
interface kr.spring.dbox.vo.DboxValidationGroup_2 {
}
class kr.spring.dbox.service.DboxServiceImpl {
~ DboxMapper dboxMapper
~ SubscriptionMapper subscriptionMapper
~ MemberMapper memberMapper
~ NotifyMapper notifyMapper
~ SubscriptionService subscriptionService
+ Long insertDbox(DboxVO)
+ void updateDboxStatus(long,int)
+ void updateDboxAcomment(long,String)
+ Integer selectListCount(Map<String,Object>)
+ List<DboxVO> selectList(Map<String,Object>)
+ Integer selectAdminListCount(Map<String,Object>)
+ List<DboxVO> selectAdminList(Map<String,Object>)
+ List<DboxVO> selectStatusUpdateList(int)
+ List<DboxVO> mainDboxList()
+ DboxVO selectDbox(long)
+ List<DboxBudgetVO> selectDboxBudgets(long)
+ void insertDboxDonation(DboxDonationVO)
+ List<DboxDonationVO> selectDboxDonations(long)
+ Integer selectDboxDonationsCount(long)
+ Long selecDoantionTotal(long)
+ DboxResultVO selectDboxResult(long)
+ void updatePayStatus(long,long)
+ int getDboxCountbyMem_num(Map<String,Object>)
+ List<DboxVO> getDboxByMem_num(Map<String,Object>)
+ List<DboxDonationVO> getDboxDonationVODboxNum(long)
+ void refund(RefundVO,DboxDonationVO)
}


interface kr.spring.dbox.service.DboxService {
+ Long insertDbox(DboxVO)
+ void updateDboxStatus(long,int)
+ void updateDboxAcomment(long,String)
+ Integer selectListCount(Map<String,Object>)
+ List<DboxVO> selectList(Map<String,Object>)
+ Integer selectAdminListCount(Map<String,Object>)
+ List<DboxVO> selectAdminList(Map<String,Object>)
+ List<DboxVO> selectStatusUpdateList(int)
+ DboxVO selectDbox(long)
+ List<DboxVO> mainDboxList()
+ List<DboxBudgetVO> selectDboxBudgets(long)
+ void insertDboxDonation(DboxDonationVO)
+ List<DboxDonationVO> selectDboxDonations(long)
+ Integer selectDboxDonationsCount(long)
+ Long selecDoantionTotal(long)
+ DboxResultVO selectDboxResult(long)
+ void updatePayStatus(long,long)
+ int getDboxCountbyMem_num(Map<String,Object>)
+ List<DboxVO> getDboxByMem_num(Map<String,Object>)
+ List<DboxDonationVO> getDboxDonationVODboxNum(long)
+ void refund(RefundVO,DboxDonationVO)
}

class kr.spring.dbox.vo.DboxDonationVO {
- long dbox_do_num
- long dbox_num
- long mem_num
- long dbox_do_price
- int dbox_do_point
- String dbox_imp_uid
- String dbox_do_comment
- int dbox_do_status
- int dbox_do_annony
- Date dbox_do_reg_date
- String mem_nick
- String mem_photo
}

class kr.spring.dbox.vo.DboxResultVO {
- long dbox_num
- long dbox_res_total
- int dbox_res_count
- String dbox_res_report
}

interface kr.spring.dbox.dao.DboxMapper {
+ Long selectDboxNum()
+ Long insertDbox(DboxVO)
+ void insertDboxBudget(DboxBudgetVO)
+ Long curDboxNum()
+ void updateDboxStatus(long,int)
+ void updateDboxAcomment(long,String)
+ Integer selectListCount(Map<String,Object>)
+ List<DboxVO> selectList(Map<String,Object>)
+ Integer selectAdminListCount(Map<String,Object>)
+ List<DboxVO> selectAdminList(Map<String,Object>)
+ List<DboxVO> selectStatusUpdateList(int)
+ List<DboxVO> mainDboxList()
+ DboxVO selectDbox(long)
+ List<DboxBudgetVO> selectDboxBudgets(long)
+ void insertDboxDonation(DboxDonationVO)
+ List<DboxDonationVO> selectDboxDonations(long)
+ Integer selectDboxDonationsCount(long)
+ Long selecDoantionTotal(long)
+ DboxResultVO selectDboxResult(long)
+ void updatePayStatus(long,long)
+ int getDboxCountbyMem_num(Map<String,Object>)
+ List<DboxVO> getDboxByMem_num(Map<String,Object>)
+ List<DboxDonationVO> getDboxDonationVODboxNum(long)
}

class kr.spring.dbox.controller.DboxController {
- DboxService dboxService
- CategoryService categoryService
- NotifyService notifyService
+ DboxVO initCommand()
+ String list()
+ String detailContent(long,Model,HttpSession)
+ String detailDonators(long,Model,HttpSession)
+ String detailNews(long,Model,HttpSession)
+ String donation(long,Model)
+ String proposeForm()
+ String proposeStep1(HttpSession,Model)
+ String Step1Submit(DboxVO,BindingResult,HttpSession)
+ String proposeStep2(HttpSession)
+ String Step2Submit(DboxVO,BindingResult,HttpSession,HttpServletRequest)
+ String proposeStep3(HttpSession)
+ String Step3Submit(DboxVO,BindingResult,HttpSession,HttpServletRequest)
+ String proposeEnd(HttpSession,Model)
+ String proposeExample(long,Model,HttpSession)
}


class kr.spring.dbox.vo.DboxReplyVO {
- int dbox_re_num
- long dbox_num
- long mem_num
- String dbox_re_content
- Date dbox_re_rdate
- Date dbox_re_mdate
- String dbox_re_ip
}

class kr.spring.dbox.vo.DboxBudgetVO {
- String dbox_bud_purpose
- long dbox_bud_price
- long dbox_num
}

class kr.spring.dbox.controller.DboxAdiminController {
- DboxService dboxService
~ NotifyService notifyService
~ SubscriptionService subscriptionService
~ MemberService memberService
+ String dboxAdmin(int,int,List<Integer>,String,String,HttpSession,Model)
+ String statusAdmin(long,Model)
+ String statusChange(long,int,String)
+ void dboxUpdate()
}


class kr.spring.dbox.vo.DboxFavVO {
- long dbox_num
- long mem_num
}

class kr.spring.dbox.controller.DboxAjaxController {
- DboxService dboxService
- CategoryService categoryService
- PointService pointService
- MemberService memberService
- NotifyService notifyService
- IamportClient impClient
- String apiKey
- String secretKey
+ Map<String,Object> getList(int,int,int,String,String,String,HttpSession)
+ void initImp()
+ IamportResponse<Payment> validateIamportWrite(String,Map<String,Object>,HttpSession,HttpServletRequest)
+ Map<String,String> dboxDonation(Map<String,Object>,HttpSession,HttpServletRequest)
}


class kr.spring.dbox.vo.DboxVO {
- long dbox_num
- long mem_num
- long dcate_num
- int dbox_team_type
- String dbox_team_name
- String dbox_team_detail
- String dbox_team_photo
- String dbox_business_rnum
- String dbox_title
- String dbox_photo
- String dbox_content
- String dbox_business_plan
- String dbox_budget_data
- String dbox_bank
- String dbox_account
- String dbox_account_name
- String dbox_comment
- long dbox_goal
- String dbox_sdate
- String dbox_edate
- Date dbox_rdate
- int dbox_status
- String dbox_acomment
- MultipartFile dbox_team_photo_file
- MultipartFile dbox_business_plan_file
- MultipartFile dbox_budget_data_file
- MultipartFile dbox_photo_file
- DboxBudgetVO dboxBudget
- List<DboxBudgetVO> dboxBudgets
- String dcate_name
- String dcate_icon
- long total
}

interface kr.spring.dbox.vo.DboxValidationGroup_3 {
}


kr.spring.dbox.service.DboxService <|.. kr.spring.dbox.service.DboxServiceImpl
@enduml