@startuml
interface kr.spring.delete.dao.DeleteMapper {
+ void deleteChatReadsByMember(long)
+ void deleteVerifyRptsByMember(long)
+ void deleteVerifiesByMember(long)
+ void updateChalJoinStatusesByMember(long)
+ List<Long> selectChallengesByMember(long)
+ List<ChallengePaymentVO> selectChalPayListByChalNum(long)
+ List<ChallengePaymentVO> selectNonLeaderChallengesByMember(long)
+ void deleteInquiriesByMember(long)
+ void deleteNotifyLogsByMember(long)
+ void deletePayUidsByMember(long)
+ void deletePointLogsByMember(long)
+ void deleteRefundsByMember(long)
+ void deleteReportsByMember(long)
+ void cancelSubscriptionByMember(long)
}

@enduml