@startuml
class kr.spring.main.controller.CommonController {
+ Map<String,Object> uploadImage(MultipartFile,HttpSession,HttpServletRequest,HttpServletResponse)
}

class kr.spring.main.controller.MainController {
~ DataService dataService
- ChallengeService challengeService
- GoodsService goodsService
- DboxService dboxService
- CategoryService categoryService
+ String init()
+ String main(Model)
+ String adminMain()
+ String main2()
}


@enduml