@startuml
interface kr.spring.payuid.dao.PayuidMapper {
+ void registerPayUId(PayuidVO)
+ void deletePayuid(String)
+ List<PayuidVO> getPayUId(long)
+ PayuidVO getPayuidByMethod(PayuidVO)
+ PayuidVO getPayuidVOByPayuid(String)
+ String generateUUIDFromMem_num(long)
}

class kr.spring.payuid.vo.PayuidVO {
- String pay_uid
- long mem_num
- String card_nickname
- String easypay_method
- String sub_method
}

interface kr.spring.payuid.service.PayuidService {
+ void registerPayUId(PayuidVO)
+ void deletePayuid(String)
+ List<PayuidVO> getPayUId(long)
+ PayuidVO getPayuidByMethod(PayuidVO)
+ PayuidVO getPayuidVOByPayuid(String)
+ String generateUUIDFromMem_num(long)
}

class kr.spring.payuid.controller.PayuidController {
- PayuidService payuidService
}

class kr.spring.payuid.service.PayuidServiceImpl {
~ PayuidMapper payuidMapper
+ void registerPayUId(PayuidVO)
+ void deletePayuid(String)
+ List<PayuidVO> getPayUId(long)
+ PayuidVO getPayuidByMethod(PayuidVO)
+ PayuidVO getPayuidVOByPayuid(String)
+ String generateUUIDFromMem_num(long)
}




kr.spring.payuid.service.PayuidService <|.. kr.spring.payuid.service.PayuidServiceImpl
@enduml