@startuml
class kr.spring.util.RCodeGenerator {
- {static} String CHARACTERS
- {static} int CODE_LENGTH
- {static} Random RANDOM
+ {static} String generateRCode()
}


class kr.spring.util.DurationFromNow {
+ {static} String getTimeDiffLabel(String)
+ {static} String getTimeDiffLabel(Date)
+ {static} String getTimeDiffLabel(String,String)
+ {static} String getTimeDiffLabel(Date,Date)
}

class kr.spring.util.CaptchaUtil {
+ {static} String get(String,Map<String,String>)
+ {static} byte[] getCaptchaImage(String,Map<String,String>)
- {static} byte[] getImage(InputStream)
- {static} HttpURLConnection connect(String)
- {static} String readBody(InputStream)
}

class kr.spring.util.PagingUtil {
- int startRow
- int endRow
- StringBuffer page
+ <<Create>> PagingUtil(int,int,int)
+ <<Create>> PagingUtil(int,int,int,int,String)
+ <<Create>> PagingUtil(int,int,int,int,String,String)
+ <<Create>> PagingUtil(String,String,int,int,int,int,String)
+ <<Create>> PagingUtil(String,String,int,int,int,int,String,String)
+ StringBuffer getPage()
+ int getStartRow()
+ int getEndRow()
}


class kr.spring.util.AuthCheckException {
}
class kr.spring.util.FileUtil {
- {static} String UPLOAD_PATH
+ {static} String createFile(HttpServletRequest,MultipartFile)
+ {static} String createFileDbox(HttpServletRequest,MultipartFile)
+ {static} void removeFile(HttpServletRequest,String)
+ {static} void removeFileDbox(HttpServletRequest,String)
+ {static} byte[] getBytes(String)
}


class kr.spring.util.StringUtil {
+ {static} String useBrHtml(String)
+ {static} String useBrNoHTML(String)
+ {static} String useNoHTML(String)
+ {static} String parseQuot(String)
}



kr.spring.util.Exception <|-- kr.spring.util.AuthCheckException
@enduml