@startuml
class kr.spring.view.DownloadView {
# void renderMergedOutputModel(Map<String,Object>,HttpServletRequest,HttpServletResponse)
}

class kr.spring.view.ImageView {
# void renderMergedOutputModel(Map<String,Object>,HttpServletRequest,HttpServletResponse)
}



org.springframework.web.servlet.view.AbstractView <|-- kr.spring.view.DownloadView
org.springframework.web.servlet.view.AbstractView <|-- kr.spring.view.ImageView
@enduml