-- FINAL_TABLE.sql와 관련된 시퀀스 작성

CREATE SEQUENCE CHAL_REVIEW_SEQ;

CREATE SEQUENCE CHALLENGE_SEQ;

CREATE SEQUENCE CHAL_JOIN_SEQ;

CREATE SEQUENCE CHAL_PAYMENT_SEQ;

CREATE SEQUENCE CHAL_VERIFY_SEQ;

CREATE SEQUENCE CHAL_FAV_SEQ;

CREATE SEQUENCE INQUIRY_SEQ;

CREATE SEQUENCE POINT_LOG_SEQ;

CREATE SEQUENCE DB_POINT_EVENT_SEQ;

CREATE SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE CHAL_CHAT_SEQ;

CREATE SEQUENCE DB_PREFERENCE_SEQ;

CREATE SEQUENCE CHAL_CATEGORY_SEQ;

CREATE SEQUENCE DONA_CATEGORY_SEQ;

CREATE SEQUENCE SUB_PAYMENT_SEQ;

CREATE SEQUENCE SUBSCRIPTION_SEQ;

CREATE SEQUENCE DBOX_SEQ;

CREATE SEQUENCE DBOX_BUDGET_SEQ;

CREATE SEQUENCE GORDER_SEQ;

CREATE SEQUENCE GORDER_DETAIL_SEQ;

CREATE SEQUENCE CART_SEQ;

CREATE SEQUENCE ITEM_SEQ;

CREATE SEQUENCE REPORT_SEQ;

CREATE SEQUENCE DBOX_REPLY_SEQ;

CREATE SEQUENCE DBOX_DONATION_SEQ;

CREATE SEQUENCE faq_seq;